import Head from 'next/head';
import Card from '../components/Card';
import { useEffect } from 'react';
import { GetStaticProps } from 'next';
import { useTypedSelector } from '../hooks/useTypedSelector';
import { ICard, ICards } from '../types';
import Layout from '../components/Layout';
import axios from 'axios';
import useActions from '../hooks/useActions';

export default function Home({ cardsResponse }) {
  const cards = useTypedSelector(state => state.cards.items);
  const { setCards } = useActions();

  useEffect(() => {
    setCards(
      cardsResponse.carts.map((item) => {
        return item.products;
      }),
    );
  }, []);

  return (
    <>
      <Head>
        <title>Marcketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main className="main">
          <section className="main__catalog catalog">
            <div className="catalog__header">
              <h1 className="catalog__header-title">
                Все товары
              </h1>
            </div>
            <div className="catalog__products products-catalog">
              {cards.map((item) => {
                return item.map((item: ICard) => {
                  return <Card key={item.id} id={item.id} title={item.title} price={item.price} />;
                });
              })}
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}

export const getServerSideProps: GetStaticProps = async () => {
  const response: ICards[] = await axios.get('https://dummyjson.com/carts').then((res) => res.data);

  return {
    props: {
      cardsResponse: response,
    },
  };
};
